# Llama 3 model with Alpaca-style LoRA training

base_model:  NousResearch/Meta-Llama-3-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer  # PreTrainedTokenizerFast

# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: true
load_in_4bit: false  # Disable 4-bit quantization (QLoRA-specific)
strict: false

datasets:
  - path: /workspace/data/FineTuningTrial/learning_json/llm_friendly_dataset.jsonl
    type: alpaca
    field_instruction: instruction
    field_input: input
    field_output: output

dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/out/lora-llama3-70b


adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_modules_to_save:
  - embed_tokens
  - lm_head

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 100
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
s2_attention:

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0

fsdp: []  # Set to an empty list instead of 'false'
gradient_checkpointing: true  # Enable memory-efficient training

special_tokens:
  pad_token: <|end_of_text|>
