### Continous pre-training: Mistral code

# start:
# cd /workspace/axolotl
# axolotl train /workspace/FineTuningTrial/axolotl/config1d.yml

# [INST] List all the capitals of Europe.  Give a quick explanation of each city and it's population.  [/INST] 

tokenizer_type: AutoTokenizer

base_model: mistralai/Mamba-Codestral-7B-v0.1
adapter: lora

load_in_8bit: true
load_in_4bit: false
strict: false

pretraining_dataset:
  - path: json
    type: pretrain
    data_files:
      - /workspace/data/FineTuningTrial/learning_json/pretrain_dataset.jsonl

      
dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir: ./outputs/config1d

adapter: lora
lora_model_dir:

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 500
max_steps: 500
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

eval_strategy: "no"
val_set_size: 0.05  # 5% of data used for validation  

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: false

loss_watchdog_threshold: 50
loss_watchdog_patience: 30

warmup_steps: 10
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
