base_model: bigcode/starcoder2-3b
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /workspace/data/FineTuningTrial/learning_json/llm_friendly_dataset.jsonl
    type: alpaca
    field_instruction: instruction
    field_input: input
    field_output: output

dataset_prepared_path:
val_set_size: 0.2
output_dir: ./outputs/qlora-starcoder2-3B

adapter: qlora
lora_model_dir:

#### TOO SMALL!!! Shoudl probably not do that on bigger data
sample_packing_size: 4  # Adjust this based on token limits
eval_sample_packing: False


sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 20
evals_per_epoch: 4
eval_steps:
eval_table_size:
saves_per_epoch: 4
save_steps:
save_total_limit: 2
debug:
deepspeed:
weight_decay:
fsdp: []  # Set to an empty list instead of 'false'
gradient_checkpointing: true  # Enable memory-efficient training

special_tokens:
  pad_token: "<|end_of_text|>"